# Site settings
email: test
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:
post_default_img: /img/see.jpg

# SEO settings
title: OMπ
description: 
url: "https://waggi43.github.io/"
twitter_username: 
default_img: 

# Profile settings
name: Max Mustermann
profile_img: /img/profil.jpg
profile: "<h3>Diavorträge Max Mustermann</h3><i>Eine Reise um die Welt in Bildern</i>"
social:
  github: 

# Build settings
include: ['.htaccess']
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
